remote_theme: just-the-docs/just-the-docs
title: JWP Applicaster Playbook
description: A playbook for developing mobile apps using Applicaster and JW Player.
baseurl: "/jwp-applicaster-docs" # the subpath of your site, e.g. /blog
url: "https://marcovandeveen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
exclude: [README.md]
# Aux links for the upper right navigation
aux_links:
  "Applicaster":
    - "https://www.applicaster.com"
  "JW Player": 
    - "https://www.jwplayer.com"
    
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/marcovandeveen/jwp-applicaster-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
