remote_theme: just-the-docs/just-the-docs
title: JWP Applicaster Playbook
description: A playbook for developing mobile apps using Applicaster and JW Player.
baseurl: "/jwp-applicaster-docs" # the subpath of your site, e.g. /blog
url: "https://marcovandeveen.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"
  "Features":
    - "https://view.monday.com/2481297474-5632cf30002ab703b130fc91726fc618?r=use1"
  "Applicaster":
    - "https://www.applicaster.com"
  "JW Player": 
    - "https://www.jwplayer.com"
