remote_theme: just-the-docs/just-the-docs
title: JW Player - Applicaster Docs
description: A Jekyll theme for documentation
baseurl: "/jwp-applicaster-docs" # the subpath of your site, e.g. /blog
url: "https://marcovandeveen.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Define Jekyll collections
